# Generated by Django 4.2.5 on 2023-10-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_resume_experience_alter_aboutme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
