# Generated by Django 4.2.5 on 2023-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='greetings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
