# Generated by Django 4.2.5 on 2023-10-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_homepage_greetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.TextField(max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
