# Generated by Django 4.2.5 on 2023-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_greetings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greetings',
            options={'verbose_name': 'Greeting', 'verbose_name_plural': 'Greetings'},
        ),
        migrations.AlterField(
            model_name='greetings',
            name='greeting',
            field=models.CharField(max_length=255),
        ),
    ]
