# Generated by Django 4.2.5 on 2023-10-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_greetings_options_alter_greetings_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='myworks',
            name='image',
            field=models.ImageField(null=True, upload_to='my_works'),
        ),
    ]
