# Generated by Django 4.2.5 on 2023-10-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_myworks_image'),
        ('website', '0010_skilllevel_display_order'),
    ]

    operations = [
    ]
