# Generated by Django 4.2.5 on 2023-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
