# Generated by Django 4.2.5 on 2023-10-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_resume_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resume'},
        ),
    ]
