# Generated by Django 4.2.5 on 2023-12-06 09:27

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_resume_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='image',
            field=models.ImageField(null=True, upload_to=website.models.custom_upload_name),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, upload_to=website.models.custom_upload_name),
        ),
    ]
