# Generated by Django 4.2.5 on 2023-12-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_myworks_image_alter_resume_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myworks',
            name='image',
            field=models.ImageField(null=True, upload_to='my_work'),
        ),
    ]
